In [1]:
!pip install numpy

Requirement already satisfied: numpy in c:\users\sashi\desktop\new folder (4)\project2.6\env\lib\site-packages (1.26.1)

In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\sashi\desktop\new folder (4)\project2.6\env\lib\site-packages (2.1.2)
Requirement already satisfied: numpy<2,>=1.22.4 in c:\users\sashi\desktop\new folder (4)\project2.6\env\lib\site-packages (from pandas) (1.26.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sashi\desktop\new folder (4)\project2.6\env\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\sashi\desktop\new folder (4)\project2.6\env\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\sashi\desktop\new folder (4)\project2.6\env\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\sashi\desktop\new folder (4)\project2.6\env\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [3]:
import numpy as np
import pandas as pd

In [4]:
data = pd.read_csv('https://raw.githubusercontent.com/Umang-19/devjam/main/public/mldata.csv', encoding='latin-1')

In [5]:
data.head()

,Logical quotient rating,hackathons,coding skills rating,public speaking points,self-learning capability?,Extra-courses did,certifications,workshops,reading and writing skills,memory capability score,Interested subjects,interested career area,Type of company want to settle in?,Taken inputs from seniors or elders,Interested Type of Books,Management or Technical,hard/smart worker,worked in teams ever?,Introvert,Suggested Job Role
0,5,0,6,2,yes,no,information security,testing,poor,poor,programming,testing,BPA,no,Series,Management,smart worker,yes,no,Applications Developer
1,7,6,4,3,no,yes,shell programming,testing,excellent,medium,Management,system developer,Cloud Services,yes,Autobiographies,Technical,hard worker,no,yes,Applications Developer
2,2,3,9,1,no,yes,information security,testing,excellent,poor,data engineering,Business process analyst,product development,yes,Travel,Technical,smart worker,no,no,Applications Developer
3,2,6,3,5,no,yes,r programming,database security,excellent,poor,networks,testing,Testing and Maintainance Services,yes,Guide,Management,smart worker,yes,yes,Applications Developer
4,2,0,3,4,yes,no,distro making,game development,excellent,medium,Software Engineering,system developer,BPA,no,Health,Technical,hard worker,yes,no,Applications Developer

In [6]:
columns_to_dummify = ['self-learning capability?', 'Extra-courses did','certifications','workshops','reading and writing skills','interested career area ','memory capability score','Interested subjects','Type of company want to settle in?','Taken inputs from seniors or elders','Interested Type of Books','Management or Technical','hard/smart worker','worked in teams ever?','Introvert']
data = pd.get_dummies(data, columns=columns_to_dummify)
data = data.replace({True:1 , False:0})
data.head()

,Logical quotient rating,hackathons,coding skills rating,public speaking points,Suggested Job Role,self-learning capability?_no,self-learning capability?_yes,Extra-courses did_no,Extra-courses did_yes,certifications_app development,...,Interested Type of Books_Travel,Interested Type of Books_Trilogy,Management or Technical_Management,Management or Technical_Technical,hard/smart worker_hard worker,hard/smart worker_smart worker,worked in teams ever?_no,worked in teams ever?_yes,Introvert_no,Introvert_yes
0,5,0,6,2,Applications Developer,0,1,1,0,0,...,0,0,1,0,0,1,0,1,1,0
1,7,6,4,3,Applications Developer,1,0,0,1,0,...,0,0,0,1,1,0,1,0,0,1
2,2,3,9,1,Applications Developer,1,0,0,1,0,...,1,0,0,1,0,1,1,0,1,0
3,2,6,3,5,Applications Developer,1,0,0,1,0,...,0,0,1,0,0,1,0,1,0,1
4,2,0,3,4,Applications Developer,0,1,1,0,0,...,0,0,0,1,1,0,0,1,1,0

In [7]:
X = data.drop(['Suggested Job Role'], axis=1)
y = data['Suggested Job Role']

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25)

In [60]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
best_model=knn.fit(X_train, y_train)

In [61]:
best_model=knn.fit(X_train, y_train)
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\sashi\desktop\new folder (4)\project2.6\env\lib\site-packages (1.3.2)
Requirement already satisfied: numpy<2.0,>=1.17.3 in c:\users\sashi\desktop\new folder (4)\project2.6\env\lib\site-packages (from scikit-learn) (1.26.1)
Requirement already satisfied: scipy>=1.5.0 in c:\users\sashi\desktop\new folder (4)\project2.6\env\lib\site-packages (from scikit-learn) (1.11.3)
Requirement already satisfied: joblib>=1.1.1 in c:\users\sashi\desktop\new folder (4)\project2.6\env\lib\site-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\sashi\desktop\new folder (4)\project2.6\env\lib\site-packages (from scikit-learn) (3.2.0)

In [73]:
predicted_name = knn.predict([[8,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,0,1,0,1,0,1,0,1,0]])
print(f"{predicted_name}")

['UX Designer']

C:\Users\sashi\Desktop\New folder (4)\project2.6\env\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

In [52]:
print(f"{predicted_name}")

['Software Developer']

In [76]:
import joblib
joblib.dump(knn, 'knn1_model.pkl')

['knn1_model.pkl']

In [ ]:
knn.predict([[13]])